# Generated by Django 3.2.5 on 2021-12-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tkdshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adminmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('userroll', models.CharField(max_length=30)),
                ('userpic', models.ImageField(upload_to='images2/')),
                ('userdob', models.CharField(max_length=30)),
                ('useremail', models.EmailField(max_length=254)),
                ('userpassword', models.CharField(max_length=30)),
                ('userphone', models.CharField(max_length=30)),
                ('usergender', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Adminmodellist',
            },
        ),
    ]
