# Generated by Django 3.2.5 on 2021-12-07 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tkdshop', '0002_adminmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='continentlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('continentccode', models.CharField(max_length=30)),
                ('continentname', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'continentlist',
            },
        ),
        migrations.CreateModel(
            name='countrylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countryccode', models.CharField(max_length=30)),
                ('countryvalue', models.CharField(max_length=30)),
                ('countryname', models.CharField(max_length=30)),
                ('countrymcode', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'countrylist',
            },
        ),
        migrations.CreateModel(
            name='customeraddresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('useraddressno', models.CharField(max_length=3000)),
                ('useraddress', models.CharField(max_length=3000)),
                ('usercountry', models.CharField(max_length=3000)),
                ('userstate', models.CharField(max_length=3000)),
                ('userpincode', models.CharField(max_length=3000)),
            ],
            options={
                'db_table': 'customeraddresseslist',
            },
        ),
        migrations.CreateModel(
            name='customerdeatail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('userpic', models.ImageField(upload_to='images2/')),
                ('userdob', models.CharField(max_length=30)),
                ('useremail', models.EmailField(max_length=254)),
                ('userpassword', models.CharField(max_length=30)),
                ('userphone', models.CharField(max_length=30)),
                ('usergender', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'customerdeataillist',
            },
        ),
        migrations.DeleteModel(
            name='Adminmodel',
        ),
    ]
