# Generated by Django 3.2.5 on 2021-12-07 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tkdshop', '0003_auto_20211208_0208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='continentlist',
            old_name='continentccode',
            new_name='countryname',
        ),
    ]
