# Generated by Django 3.2.5 on 2021-12-08 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tkdshop', '0004_rename_continentccode_continentlist_countryname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdeatail',
            name='userpic',
            field=models.ImageField(upload_to='customer/pic/'),
        ),
    ]
