# Generated by Django 3.2.5 on 2021-12-14 23:40

from django.db import migrations, models
import tkdshop.models


class Migration(migrations.Migration):

    dependencies = [
        ('tkdshop', '0007_auto_20211211_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdeatail',
            name='userpic',
            field=models.ImageField(blank=True, default='customer/pic/default.jpg', null=True, upload_to=tkdshop.models.photo_path),
        ),
    ]
