# Generated by Django 3.2.5 on 2021-12-18 03:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tkdshop', '0008_alter_customerdeatail_userpic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customeraddresses',
            old_name='userpincode',
            new_name='userzipcode',
        ),
        migrations.AddField(
            model_name='customeraddresses',
            name='useraddressprimary',
            field=models.CharField(default=django.utils.timezone.now, max_length=3000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customeraddresses',
            name='usercity',
            field=models.CharField(default=django.utils.timezone.now, max_length=3000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customeraddresses',
            name='userid',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
