# Generated by Django 3.2.5 on 2021-12-18 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tkdshop', '0009_auto_20211218_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddresses',
            name='useraddressprimary',
            field=models.BooleanField(default=False),
        ),
    ]
