# Generated by Django 3.2.5 on 2021-12-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tkdshop', '0010_alter_customeraddresses_useraddressprimary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddresses',
            name='useraddressprimary',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
