# Generated by Django 3.2.5 on 2021-12-22 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tkdshop', '0011_alter_customeraddresses_useraddressprimary'),
    ]

    operations = [
        migrations.CreateModel(
            name='customerpayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=30)),
                ('userpaymentno', models.CharField(max_length=3000)),
                ('userpaymentprimary', models.BooleanField(blank=True, default=False)),
                ('usercardtype', models.CharField(max_length=3000)),
                ('usercardnumber', models.CharField(max_length=3000)),
                ('usercardname', models.CharField(max_length=3000)),
                ('usercardcvc', models.CharField(max_length=3000)),
                ('usercarddate', models.CharField(max_length=3000)),
            ],
            options={
                'db_table': 'customerpaymentlist',
            },
        ),
    ]
