# Generated by Django 3.2.5 on 2021-12-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tkdshop', '0015_product_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productrating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Productid', models.SlugField(max_length=150)),
                ('userid', models.SlugField(max_length=150)),
                ('userrating', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'Productratinglist',
            },
        ),
    ]
