# Generated by Django 3.2.5 on 2021-12-28 15:25

from django.db import migrations, models
import django.utils.timezone
import tkdshop.models


class Migration(migrations.Migration):

    dependencies = [
        ('tkdshop', '0017_product_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categorygender',
        ),
        migrations.RemoveField(
            model_name='product',
            name='categorytype',
        ),
        migrations.RemoveField(
            model_name='product',
            name='maincategory',
        ),
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='product',
            name='categoryid',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='categorygender',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='category',
            name='categorytype',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='category',
            name='subcategory',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='customer/pic/default.jpg', null=True, upload_to=tkdshop.models.productpath),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='userid',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='productrating',
            name='Productid',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='productrating',
            name='userid',
            field=models.CharField(max_length=150),
        ),
    ]
