# Generated by Django 3.2.5 on 2021-12-29 00:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tkdshop', '0018_auto_20211228_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrating',
            name='userrating1',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], default=django.utils.timezone.now, max_length=2),
            preserve_default=False,
        ),
    ]
