# Generated by Django 3.2.5 on 2021-12-29 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tkdshop', '0019_productrating_userrating1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productrating',
            name='userrating1',
        ),
        migrations.AddField(
            model_name='productrating',
            name='Rules',
            field=models.CharField(blank=True, choices=[(1, 'At least one order'), (2, 'Have reward points')], max_length=100, verbose_name='Select rules for customer segmentation'),
        ),
    ]
