# Generated by Django 3.2.5 on 2021-12-29 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tkdshop', '0021_auto_20211229_0709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productrating',
            name='my_field',
        ),
        migrations.RemoveField(
            model_name='productrating',
            name='my_field2',
        ),
    ]
