# Generated by Django 3.2.5 on 2021-12-29 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tkdshop', '0022_auto_20211229_0711'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Productrating',
        ),
    ]
