# Generated by Django 3.2.5 on 2021-12-29 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tkdshop', '0024_productrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrating',
            name='publications',
            field=models.ManyToManyField(to='tkdshop.Category'),
        ),
    ]
