# Generated by Django 3.2.5 on 2021-12-29 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tkdshop', '0025_productrating_publications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrating',
            name='publications',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='tkdshop.Category', verbose_name='user permissions'),
        ),
    ]
