# Generated by Django 3.2.5 on 2021-12-29 02:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tkdshop', '0026_alter_productrating_publications'),
    ]

    operations = [
        migrations.CreateModel(
            name='opetest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Some words about quiz', verbose_name='Test description')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('estimate', models.IntegerField(default=0, help_text="Estimate time in hours. '0' - unlimited")),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('students', models.ManyToManyField(blank=True, related_name='opetests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='productrating',
            name='my_field',
        ),
        migrations.RemoveField(
            model_name='productrating',
            name='my_field2',
        ),
        migrations.RemoveField(
            model_name='productrating',
            name='publications',
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_flag', models.BooleanField()),
                ('ope', models.ManyToManyField(to='tkdshop.opetest')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
