# Generated by Django 3.2.5 on 2021-12-29 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tkdshop', '0027_auto_20211229_0755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opetest',
            name='author',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
    ]
