# Generated by Django 3.2.5 on 2021-12-29 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tkdshop', '0029_auto_20211229_0807'),
    ]

    operations = [
        migrations.CreateModel(
            name='opetest',
            fields=[
                ('catagory_id', models.AutoField(primary_key=True, serialize=False)),
                ('catagory_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('catagory_id', models.AutoField(primary_key=True, serialize=False)),
                ('catagory_name', models.ManyToManyField(to='tkdshop.opetest')),
            ],
        ),
    ]
