# Generated by Django 3.2.5 on 2021-12-29 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tkdshop', '0034_auto_20211229_0835'),
    ]

    operations = [
        migrations.CreateModel(
            name='opetest',
            fields=[
                ('catagory_id', models.AutoField(primary_key=True, serialize=False)),
                ('catagory_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('catagory_id', models.AutoField(primary_key=True, serialize=False)),
                ('catagory_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tkdshop.opetest')),
            ],
        ),
    ]
