# Generated by Django 3.2.5 on 2021-12-29 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tkdshop', '0035_opetest_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='catagory_name',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='catagory_name',
            field=models.ManyToManyField(to='tkdshop.opetest'),
        ),
    ]
