# Generated by Django 3.2.5 on 2021-12-29 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tkdshop', '0037_auto_20211229_0850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('catagory_id', models.AutoField(primary_key=True, serialize=False)),
                ('catagory_name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'Categorylist',
            },
        ),
    ]
