# Generated by Django 3.2.5 on 2021-12-29 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tkdshop', '0038_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
