# Generated by Django 3.2.5 on 2021-12-29 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tkdshop', '0040_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
