# Generated by Django 3.2.5 on 2021-12-30 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tkdshop', '0043_delete_productrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivered',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='payondelivery',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='replacement',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty',
            field=models.BooleanField(default=True),
        ),
    ]
