# Generated by Django 3.2.5 on 2021-12-30 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tkdshop', '0045_alter_product_warranty'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
