# Generated by Django 3.2.5 on 2021-12-30 04:08

import computed_property.fields
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tkdshop', '0047_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_id',
            field=computed_property.fields.ComputedCharField(compute_from='categoryid', default="kousjh", editable=False, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='price_save',
            field=computed_property.fields.ComputedDecimalField(compute_from='pricesave', decimal_places=2, default=15.22, editable=False, max_digits=10),
            preserve_default=False,
        ),
    ]
