# Generated by Django 3.2.5 on 2021-12-30 04:12

import computed_property.fields
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tkdshop', '0048_auto_20211230_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='your_price',
            field=computed_property.fields.ComputedDecimalField(compute_from='yourprice', decimal_places=2, default=15.22, editable=False, max_digits=10),
            preserve_default=False,
        ),
    ]
