# Generated by Django 3.2.5 on 2021-12-30 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tkdshop', '0049_product_your_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
