# Generated by Django 3.2.5 on 2021-12-30 04:15

import computed_property.fields
from django.db import migrations, models
import multiselectfield.db.fields
import tkdshop.models


class Migration(migrations.Migration):

    dependencies = [
        ('tkdshop', '0050_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Product_id', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.CharField(max_length=150)),
                ('product_gender', multiselectfield.db.fields.MultiSelectField(choices=[['all', 'All'], ['male', 'Male'], ['female', 'Female'], ['kid', 'Kids'], ['others', 'Others']], max_length=26)),
                ('brand', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available', models.BooleanField(default=True)),
                ('payondelivery', models.BooleanField(default=True)),
                ('replacement', models.BooleanField(default=True)),
                ('delivered', models.BooleanField(default=True)),
                ('warranty', models.PositiveIntegerField()),
                ('stock', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, default='customer/pic/default.jpg', null=True, upload_to=tkdshop.models.productpath)),
                ('category_id', computed_property.fields.ComputedCharField(compute_from='categoryid', editable=False, max_length=150)),
                ('price_save', computed_property.fields.ComputedDecimalField(compute_from='pricesave', decimal_places=2, editable=False, max_digits=10)),
                ('your_price', computed_property.fields.ComputedDecimalField(compute_from='yourprice', decimal_places=2, editable=False, max_digits=10)),
                ('catagory_name', models.ManyToManyField(to='tkdshop.Category')),
            ],
            options={
                'db_table': 'Productlist',
            },
        ),
    ]
