# Generated by Django 3.2.5 on 2021-12-30 10:23

import computed_property.fields
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tkdshop', '0053_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='catagory_name_list',
            field=computed_property.fields.ComputedCharField(compute_from='catagorynamelist', default=django.utils.timezone.now, editable=False, max_length=150),
            preserve_default=False,
        ),
    ]
