# Generated by Django 3.2.5 on 2021-12-30 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tkdshop', '0055_auto_20211230_1559'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
