# Generated by Django 3.2.5 on 2021-12-31 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tkdshop', '0057_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
