# Generated by Django 3.2.5 on 2022-01-01 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tkdshop', '0061_product_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='product',
            name='warranty',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
