# Generated by Django 3.2.5 on 2022-01-03 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tkdshop', '0064_auto_20220102_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customeraddtocart',
            fields=[
                ('cartid', models.AutoField(primary_key=True, serialize=False)),
                ('productid', models.CharField(max_length=150)),
                ('userid', models.CharField(max_length=150)),
                ('Productquantity', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'Customeraddtocartlist',
            },
        ),
    ]
