# Generated by Django 3.2.5 on 2022-01-03 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tkdshop', '0065_customeraddtocart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customeraddtocart',
        ),
    ]
