# Generated by Django 3.2.5 on 2022-01-03 13:51

import computed_property.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tkdshop', '0067_customeraddtocart'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddtocart',
            name='total_price',
            field=computed_property.fields.ComputedCharField(compute_from='cart_id', default='0', editable=False, max_length=150),
        ),
    ]
