# Generated by Django 3.2.5 on 2022-01-03 14:16

import computed_property.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tkdshop', '0069_auto_20220103_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddtocart',
            name='one_price',
            field=computed_property.fields.ComputedCharField(compute_from='oneprice', default='0', editable=False, max_length=150),
        ),
    ]
