# Generated by Django 3.2.5 on 2022-01-03 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tkdshop', '0071_auto_20220104_0128'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customeraddtocart',
        ),
    ]
