# Generated by Django 3.2.5 on 2022-01-03 20:00

import computed_property.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tkdshop', '0072_delete_customeraddtocart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customeraddtocart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productid', models.CharField(max_length=150)),
                ('userid', models.CharField(max_length=150)),
                ('Productquantity', models.PositiveIntegerField(default=1000)),
                ('cartid', computed_property.fields.ComputedCharField(compute_from='cart_id', editable=False, max_length=150)),
                ('total_price', computed_property.fields.ComputedDecimalField(compute_from='totalprice', decimal_places=2, default='0', editable=False, max_digits=10)),
                ('one_price', computed_property.fields.ComputedDecimalField(compute_from='oneprice', decimal_places=2, default='0', editable=False, max_digits=10)),
            ],
            options={
                'db_table': 'Customeraddtocartlist',
            },
        ),
    ]
