# Generated by Django 3.2.5 on 2022-01-04 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tkdshop', '0075_customeraddtocart'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdeatail',
            name='userrewardpoints',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
