# Generated by Django 3.2.5 on 2022-01-20 18:03

import computed_property.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tkdshop', '0076_customerdeatail_userrewardpoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpayment',
            name='usercardcvc_format',
            field=computed_property.fields.ComputedCharField(compute_from='usercardcvcformat', default='', editable=False, max_length=150),
        ),
        migrations.AddField(
            model_name='customerpayment',
            name='usercardnumber_format',
            field=computed_property.fields.ComputedCharField(compute_from='usercardnumberformat', default='', editable=False, max_length=150),
        ),
    ]
