# Generated by Django 3.2.5 on 2022-01-20 18:18

import computed_property.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tkdshop', '0077_auto_20220120_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpayment',
            name='usercardcvc_format',
            field=computed_property.fields.ComputedCharField(compute_from='usercardcvcformat', editable=False, max_length=150),
        ),
        migrations.AlterField(
            model_name='customerpayment',
            name='usercardnumber_format',
            field=computed_property.fields.ComputedCharField(compute_from='usercardnumberformat', editable=False, max_length=150),
        ),
    ]
