# Generated by Django 3.2.5 on 2022-01-22 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tkdshop', '0080_alter_customeraddtoorder_productstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddtoorder',
            name='orderid',
            field=models.CharField(max_length=150),
        ),
    ]
