# Generated by Django 3.2.5 on 2022-01-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tkdshop', '0081_alter_customeraddtoorder_orderid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddtoorder',
            name='trackingid',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='customeraddtoorder',
            name='orderid',
            field=models.CharField(default='', max_length=150),
        ),
    ]
