# Generated by Django 3.2.5 on 2022-01-23 08:11

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tkdshop', '0083_auto_20220122_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdeatail',
            name='usergender',
            field=multiselectfield.db.fields.MultiSelectField(choices=[['all', 'All'], ['male', 'Male'], ['female', 'Female'], ['kid', 'Kids'], ['others', 'Others']], default=None, max_length=26),
        ),
    ]
