# Generated by Django 3.2.5 on 2022-01-23 18:07

import computed_property.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tkdshop', '0085_alter_customerdeatail_usergender'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddtoorder',
            name='productstatuscolor',
            field=computed_property.fields.ComputedCharField(compute_from='productstatus_color', default='info', editable=False, max_length=150),
        ),
        migrations.AlterField(
            model_name='customeraddtoorder',
            name='productstatus',
            field=models.CharField(choices=[['Pending', 'Pending'], ['Awaiting Payment', 'Awaiting Payment'], ['Accepted', 'Accepted'], ['Packed', 'Packed'], ['Awaiting Shipment', 'Awaiting Shipment'], ['Shipped', 'Shipped'], ['On The Way', 'On The Way'], ['Awaiting Pickup', 'Awaiting Pickup'], ['Delivered', 'Delivered'], ['Cancel', 'Cancel'], ['Declined', 'Declined'], ['Refunded', 'Refunded']], default='Pending', max_length=150),
        ),
    ]
