# Generated by Django 3.2.5 on 2022-01-23 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tkdshop', '0087_alter_customeraddtoorder_productstatuscolor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeraddtoorder',
            name='productstatuscolor',
        ),
    ]
