# Generated by Django 3.2.5 on 2022-01-23 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tkdshop', '0088_remove_customeraddtoorder_productstatuscolor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddtoorder',
            name='productstatus',
            field=models.CharField(choices=[['Pending', 'Pending'], ['Awaiting Payment', 'Awaiting Payment'], ['Accepted', 'Accepted'], ['Packed', 'Packed'], ['Awaiting Shipment', 'Awaiting Shipment'], ['Shipped', 'Shipped'], ['On The Way', 'On The Way'], ['Awaiting Pickup', 'Awaiting Pickup'], ['Delivered', 'Delivered'], ['Cancel', 'Cancel'], ['Returned', 'Returned'], ['Refunded', 'Refunded']], default='Pending', max_length=150),
        ),
    ]
