# Generated by Django 3.2.5 on 2022-01-25 13:28

import computed_property.fields
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tkdshop', '0090_alter_customeraddtoorder_productstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='catagoryname_id',
            field=computed_property.fields.ComputedCharField(compute_from='catagorynameid', default=django.utils.timezone.now, editable=False, max_length=150),
            preserve_default=False,
        ),
    ]
