# Generated by Django 3.2.5 on 2022-01-25 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tkdshop', '0092_alter_product_catagoryname_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='catagoryname_id',
        ),
    ]
