# Generated by Django 3.2.5 on 2022-01-26 09:13

import computed_property.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tkdshop', '0097_customeraddtoorder_productstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddtoorder',
            name='productstatusdate',
            field=computed_property.fields.ComputedDecimalField(compute_from='product_status_date', decimal_places=2, default='0', editable=False, max_digits=10),
        ),
    ]
