# Generated by Django 3.2.5 on 2022-01-26 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tkdshop', '0108_productstatusmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='productstatusmodel',
        ),
    ]
