# Generated by Django 3.2.5 on 2022-01-26 21:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tkdshop', '0111_customeraddtoorder_productstatusdate'),
    ]

    operations = [
    ]
