# Generated by Django 3.2.5 on 2022-01-26 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tkdshop', '0112_auto_20220127_0302'),
    ]

    operations = [
        migrations.DeleteModel(
            name='productstatusmodel',
        ),
    ]
