# Generated by Django 3.2.5 on 2022-01-26 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tkdshop', '0113_delete_productstatusmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='productstatusmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.CharField(max_length=150)),
                ('orderdesc', models.CharField(max_length=150)),
                ('productstatustype', models.CharField(choices=[['Pending', 'Pending'], ['Accepted', 'Accepted'], ['Packed', 'Packed'], ['Shipped', 'Shipped'], ['On The Way', 'On The Way'], ['Delivered', 'Delivered'], ['Cancel', 'Cancel'], ['Returned', 'Returned'], ['Refunded', 'Refunded']], default='Pending', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'productstatuslist',
            },
        ),
    ]
