# Generated by Django 3.2.5 on 2022-01-26 21:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tkdshop', '0114_productstatusmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productstatusmodel',
            name='orderid',
        ),
        migrations.AddField(
            model_name='productstatusmodel',
            name='trackingid',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
