# Generated by Django 3.2.5 on 2022-01-27 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tkdshop', '0115_auto_20220127_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddtoorder',
            name='productstatus',
            field=models.CharField(choices=[['Pending', 'Pending'], ['Accepted', 'Accepted'], ['Packed', 'Packed'], ['Shipped', 'Shipped'], ['On The Way', 'On The Way'], ['Delivered', 'Delivered'], ['Returned Request', 'Returned Request'], ['Returned', 'Returned'], ['Refunded', 'Refunded'], ['Cancel', 'Cancel']], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='productstatusmodel',
            name='productstatustype',
            field=models.CharField(choices=[['Pending', 'Pending'], ['Accepted', 'Accepted'], ['Packed', 'Packed'], ['Shipped', 'Shipped'], ['On The Way', 'On The Way'], ['Delivered', 'Delivered'], ['Returned Request', 'Returned Request'], ['Returned', 'Returned'], ['Refunded', 'Refunded'], ['Cancel', 'Cancel']], default='Pending', max_length=150),
        ),
    ]
