# Generated by Django 3.2.5 on 2022-01-31 05:38

import computed_property.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tkdshop', '0117_customeraddtowishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productcatagory',
            field=computed_property.fields.ComputedCharField(compute_from='product_catagory', default='', editable=False, max_length=150),
        ),
    ]
