# Generated by Django 3.2.5 on 2022-01-31 05:45

import computed_property.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tkdshop', '0118_product_productcatagory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productcatagory2',
            field=computed_property.fields.ComputedCharField(compute_from='product_catagory2', default='', editable=False, max_length=150),
        ),
    ]
