# Generated by Django 3.2.5 on 2022-01-31 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tkdshop', '0120_producttogether'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='catagory_name',
        ),
        migrations.AddField(
            model_name='product',
            name='catagory_id',
            field=models.CharField(default='1', max_length=150),
        ),
    ]
