# Generated by Django 3.2.5 on 2022-01-31 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tkdshop', '0122_alter_product_catagory_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='catagory_id',
        ),
    ]
