# Generated by Django 3.2.5 on 2022-02-01 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tkdshop', '0124_product_catagory_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producttogether',
        ),
    ]
