# Generated by Django 3.2.5 on 2022-02-01 01:29

import computed_property.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tkdshop', '0125_delete_producttogether'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producttogether',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=150)),
                ('productid', models.CharField(max_length=150)),
                ('productid1', models.CharField(max_length=150)),
                ('discount', models.DecimalField(decimal_places=2, default=5, max_digits=10)),
                ('product_price', computed_property.fields.ComputedDecimalField(compute_from='productprice', decimal_places=2, default='0', editable=False, max_digits=10)),
                ('product1_price', computed_property.fields.ComputedDecimalField(compute_from='product1price', decimal_places=2, default='0', editable=False, max_digits=10)),
                ('Producttogetherid', computed_property.fields.ComputedCharField(compute_from='Producttogether_id', editable=False, max_length=150)),
                ('total_price', computed_property.fields.ComputedDecimalField(compute_from='totalprice', decimal_places=2, default='0', editable=False, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Producttogetherlist',
            },
        ),
    ]
