# Generated by Django 3.2.5 on 2022-02-01 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tkdshop', '0126_producttogether'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttogether',
            name='total_price',
        ),
    ]
