# Generated by Django 3.2.5 on 2022-02-02 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tkdshop', '0127_remove_producttogether_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='productid',
        ),
    ]
