# Generated by Django 3.2.5 on 2022-02-02 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tkdshop', '0128_remove_product_productid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productid',
            field=models.CharField(default='SCcHxemRsyi7ZWqAi4BQ', max_length=150),
        ),
    ]
