# Generated by Django 3.2.5 on 2022-02-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tkdshop', '0130_auto_20220202_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productid',
            field=models.CharField(default='Jbx7MUjI5wjfrcYRbpHx', max_length=150),
        ),
    ]
