# Generated by Django 3.2.5 on 2022-02-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tkdshop', '0135_alter_product_productid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productid',
            field=models.CharField(default='q6eJWCtEdmexwTsOjD7d', max_length=150),
        ),
    ]
