# Generated by Django 3.2.5 on 2022-02-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tkdshop', '0137_auto_20220202_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productid',
            field=models.CharField(default='s5qQ3BRbpLrvP9kBqgxb', max_length=150),
        ),
    ]
