# Generated by Django 3.2.5 on 2022-02-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tkdshop', '0138_alter_product_productid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productid',
            field=models.CharField(default='hY7qBMetFfsimYO0utlA', max_length=150),
        ),
    ]
