# Generated by Django 3.2.5 on 2022-02-03 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tkdshop', '0140_alter_product_productid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productid',
            field=models.CharField(default='BDdYGIcyB3UeV48dlgjZ', max_length=150),
        ),
    ]
