# Generated by Django 3.2.5 on 2022-02-03 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tkdshop', '0141_alter_product_productid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productid',
            field=models.CharField(default='I0CqVyTfUkTBlgpxXCzl', max_length=150),
        ),
    ]
