# Generated by Django 3.2.5 on 2022-02-03 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tkdshop', '0143_alter_product_productid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productid',
            field=models.CharField(default='VTtT1tdymGUomg12nbZ1', max_length=150),
        ),
    ]
