# Generated by Django 3.2.5 on 2022-02-05 21:29

import computed_property.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tkdshop', '0144_alter_product_productid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productid',
            field=computed_property.fields.ComputedCharField(compute_from='product_id', default='', editable=False, max_length=150),
        ),
    ]
