# Generated by Django 3.2.5 on 2022-02-05 21:53

import computed_property.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tkdshop', '0147_rename_productid_product_productid1'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productid',
            field=computed_property.fields.ComputedCharField(compute_from='product_id', default='', editable=False, max_length=150),
        ),
    ]
