# Generated by Django 3.2.5 on 2022-02-06 14:49

import computed_property.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tkdshop', '0149_auto_20220206_0324'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productid1',
            field=computed_property.fields.ComputedCharField(compute_from='product_id', default='', editable=False, max_length=150),
        ),
    ]
