# Generated by Django 3.2.5 on 2022-02-06 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tkdshop', '0150_product_productid1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='productid1',
        ),
    ]
