# Generated by Django 3.2.5 on 2022-02-06 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tkdshop', '0151_remove_product_productid1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='productcatagory',
        ),
        migrations.RemoveField(
            model_name='product',
            name='productcatagory2',
        ),
    ]
