# Generated by Django 3.2.5 on 2022-02-06 19:55

import computed_property.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tkdshop', '0152_auto_20220207_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productcatagory',
            field=computed_property.fields.ComputedCharField(compute_from='product_catagory', default='', editable=False, max_length=150),
        ),
        migrations.AddField(
            model_name='product',
            name='productcatagory2',
            field=computed_property.fields.ComputedCharField(compute_from='product_catagory2', default='', editable=False, max_length=150),
        ),
    ]
