# Generated by Django 3.2.5 on 2022-02-06 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tkdshop', '0154_auto_20220207_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productcatagory',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='productcatagory2',
            field=models.CharField(max_length=150),
        ),
    ]
